name: "Datapane Build"
description: "Build a Datapane report from a script inside your repo"
branding:
  icon: "box"
  color: "blue"
inputs:
  script:
    description: "Path to your script"
    required: true
  token:
    description: "API token"
    required: false
  server:
    description: "Datapane server host"
    default: "https://datapane.com"
    required: false
  requirements:
    description: "Script dependencies, using pip requirements syntax"
    default: "[]"
    required: false
  parameters:
    description: "Script Parameters"
    default: "{}"
    required: false
  version:
    description: "Datapane version to install, using pip specification"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"

